---
title: "Regression Analysis Past Questions and Answers"
output:
  html_document:
    mathjax: local
    self_contained: false
    toc: true
    toc_depth: 3
  pdf_document:
    toc: true
    toc_depth: '2'
---

### Question 1

A study was performed to investigate the shear strength of soil $(y)$ as it related to depth in feet $(x_1)$ and the moisture $(x_2)$. Ten observations were collected and the following summary quantities obtained: \begin{equation*}
     n=10, \sum x_{i1} = 123, \sum x_{i2} = 453, \sum x^2_{i1} = 4200.9, 
     \sum x^2_{i2} = 21729,  \newline
     \sum x_{i1}x^2_{i2} = 12252, \sum y_{i1} = 1816,
     \sum x_{i1}y_i = 43450.8, \sum x_{i2}y_i = 104636.8
     \end {equation*}

Set up the least squares normal equation and the matrix form for the model: $y = \beta_0 + \beta_1 x_1 + \beta_1 x_2 + \epsilon$

Estimate the parameters in the above model.

### Solution

In the question above, the variables in the normal equation of the regression model have already been given \begin{align*}
    \sum y_i & = n\beta_0 +\beta_1\sum x_{i1} + \beta_2\sum x_{i2} \\
    \sum x_{i1}y_i & = x_{i1}\beta_0 +\beta_1\sum x_{i1}^2 + \beta_2\sum x_{i1}x_{i2} \\
    \sum x_{i2}y_i & = x_{i2}\beta_0 +\beta_1\sum x_{i1}x_{i2} + \beta_2\sum x_{i2}^2
  \end{align*}

So now we need to write the above systems of equations in matrix form for easy evaluation \begin{equation*}
    \begin{pmatrix}
    n & \sum x_{i1} & \sum x_{i2} \\
    \sum x_{i1} & \sum x_{i1}^2 & \sum x_{i1}x_{i2}\\
    \sum x_{i2} & \sum x_{i1}x_{i2} & \sum x_{i2}^2
    \end{pmatrix}
    \begin{pmatrix}
      \beta_0\\
      \beta_1\\
      \beta_2\\
    \end{pmatrix}
    =
    \begin{pmatrix}
      \sum y_i \\
      \sum x_{i1}y_i \\
      \sum x_{i2}y_i
    \end{pmatrix}
\end{equation*}

\begin{equation*}
\Rightarrow 
  \begin{pmatrix}
      \beta_0\\
      \beta_1\\
      \beta_2\\
    \end{pmatrix}
    =
    \begin{pmatrix}
    n & \sum x_{i1} & \sum x_{i2} \\
    \sum x_{i1} & \sum x_{i1}^2 & \sum x_{i1}x_{i2}\\
    \sum x_{i2} & \sum x_{i1}x_{i2} & \sum x_{i2}^2
    \end{pmatrix}^{-1}
    
  \begin{pmatrix}
    \sum y_i \\
    \sum x_{i1}y_i \\
    \sum x_{i2}y_i
  \end{pmatrix}
\end{equation*}

Substituting the necessary values \begin{align*}
  \Rightarrow
  \begin{pmatrix}
    \beta_0\\
    \beta_1\\
    \beta_2\\
  \end{pmatrix}
  =
  \begin{pmatrix}
    10 & 123 & 453 \\
    123 & 4200.9 & 12252 \\
    453 & 12252 & 21729
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
    1816\\
    43450.8\\
    104636.8\\
  \end{pmatrix}
\end{align*}

\begin{equation*}
\Rightarrow
\begin{pmatrix}
    \beta_0\\
    \beta_1\\
    \beta_2\\
  \end{pmatrix}
=
  \begin{pmatrix}
    0.142 & -0.00695 & 0.000957 \\
    -0.00695 & -0.0000292 & 0.000161 \\
    0.000957 & 0.000161 & -0.0000649
  \end{pmatrix}
  
  \begin{pmatrix}
    1816\\
    43450.8\\
    104636.8\\
  \end{pmatrix}

\end{equation*} \begin{equation*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1\\
      \beta_2\\
    \end{pmatrix}
  =
    \begin{pmatrix}
      56.176\\
      2.995\\
      1.955\\
    \end{pmatrix}
\end{equation*}

Therefore, the correct model for the equation is $y = 56.176 + 2.995x_1 + 1.995x_2 + \epsilon$

------------------------------------------------------------------------

### Question 2

(a) Given a Non-linear regression form of $y_1 = \beta_0 e^{\beta_1x_1 +\beta_2x_2}$. Explain how to estimate the model parameter estimates

(b) Given the data sets

|                       |     |     |     |     |
|-----------------------|-----|-----|-----|-----|
| Temperature $(x_2)$   | 120 | 110 | 80  | 60  |
| Concentration $(x_1)$ | 2.5 | 3.5 | 4.0 | 5.5 |
| Yield $(y)$           | 800 | 830 | 850 | 900 |

Estimate the model $y_1 = \beta_0 e^{\beta_1x_1 +\beta_2x_2}$

### Solution

In this case, the first step is to linearise the non-linear regression form by taking the natural log \ln of both sides of the equation

$\Rightarrow   \ln y_1 = \ln\beta_0 + \beta_1x_1 + \beta_2x_2$

\begin{align*}
      \sum \ln y_1  & = \ln\beta_0 +\beta_1\sum x_{1} + \beta_2\sum x_{2} \\
      \sum x_{1}y_i & = \ln\beta_0\sum x_1 +\beta_1\sum x_{1}^2 + \beta_2\sum x_{1}x_{2} \\
      \sum x_{2}y_i & = \ln\beta_0\sum x_2 +\beta_1\sum x_1x_2 + \beta_2\sum x_{2}^2
\end{align*}

|  |  |  |  |  |  |  |  |  |
|--------|--------|--------|--------|--------|--------|--------|--------|--------|
| $y$ | $x_1$ | $x_2$ | $\ln(y)$ | $x_1\ln(y)$ | $x_2\ln(y)$ | $x_1^2$ | $x_1x_2$ | $x_2^2$ |
| 800 | 2.5 | 120 | 6.684 | 16.71 | 802.08 | 6.25 | 300 | 14400 |
| 830 | 3.5 | 110 | 6.721 | 23.5235 | 739.31 | 585 | 12100 | 12100 |
| 850 | 4.0 | 80 | 6.745 | 26.98 | 539.6 | 16 | 320 | 6400 |
| 900 | 5.5 | 60 | 6.802 | 37.411 | 408.12 | 30.25 | 166.375 | 3600 |
| $\sum =$ 3380 | 15.5 | 370 | 26.952 | 104.6245 | 2489.14 | 64.75 | 1371.375 | 36500 |

: Computation table

\begin{align*}
  \Rightarrow
  \begin{pmatrix}
    \ln\beta_0\\
    \beta_1\\
    \beta_2\\
  \end{pmatrix}
  & =
  \begin{pmatrix}
    4 & 15.5 & 370 \\
    15.5 & 64.75 & 1371.375\\
    370 & 1371.375 & 36500
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
    6.739\\
    0.026\\
    -0.001\\
  \end{pmatrix} \\
\end{align*}

\begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \ln\beta_0\\
      \beta_1\\
      \beta_2\\
    \end{pmatrix}
    & =
    \begin{pmatrix}
    6.739\\
    0.026\\
    -0.001\\
  \end{pmatrix}
\end{align*} The solution to the systems of equations above implies that $\ln(y_1) = (6.739) + 0.026x_1 + (-0.001)x_2$

Note that $\ln\beta_0 = 6.739$.

Now we need to convert the linear equation to its original exponential form \begin{align*}
e^{\ln(y_1)} & = e^{(\ln\beta_0 + 0.026x_1 + (-0.001)x_2)} \\
\Rightarrow y_1 & = e^{\ln\beta_0} e^{0.026x_1 + (-0.001)x_2} \\
\Rightarrow y_1 & = e^{(6.729)} e^{0.026x_1 - 0.001x_2} \\
\Rightarrow y_1 & = 836.310 e^{0.026x_1 - 0.001x_2} 
\end{align*}

Therefore, the model estimate is $\Rightarrow y_i =  836.310 e^{0.026x_{i1} - 0.001x_{i2}}$

------------------------------------------------------------------------

### Question 3

a.  A study was made to determine the stirring rate on the amount of impurity in paint produced by a chemical process. The study yielded the following data

|               |     |     |      |      |      |      |      |
|:-------------:|:---:|:---:|:----:|:----:|:----:|:----:|:----:|
|   Impurity    | 8.4 | 9.5 | 11.8 | 10.4 | 13.3 | 14.8 | 13.2 |
| Stirring Rate | 20  | 22  |  24  |  26  |  28  |  30  |  32  |

The model $y_i = \beta_0 + \beta_1(x_i - \bar{x}) + \epsilon_i$ was proposed. Obtain the parameter estimates.

### Solution

Given the proposed model $y_i = \beta_0 +\beta_1(x - \bar{x}) + \epsilon$ Firstly, we generate the normal equation \begin{align*}
      \sum y_i & = n\beta_0 + \beta_1 \sum (x_i - \bar{x}) \\
      \sum y_i (x_i - \bar{x}) & = \beta_0 \sum (x_i - \bar{x})  + \beta_1 \sum {(x_i - \bar{x})}^2
    \end{align*}

The systems of equation is given by \begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \sum y_i \\
      \sum y_i (x_i - \bar{x})
    \end{pmatrix}
    & =
    \begin{pmatrix}
    n & \sum (x_i - \bar{x})\\
    \sum (x_i - \bar{x}) & \sum {(x_i - \bar{x})}^2
  \end{pmatrix}
  
  \begin{pmatrix}
    \beta_0\\
    \beta_1
  \end{pmatrix}
\end{align*}

\begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
    n & \sum (x_i - \bar{x})\\
    \sum (x_i - \bar{x}) & \sum {(x_i - \bar{x})}^2
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
    \sum y_i \\
      \sum y_i (x_i - \bar{x})
  \end{pmatrix}
\end{align*}

| $y_i$ | $x_i$ | $(x_i - \bar{x})$ | $y_i(x_i - \bar{x})$ | $(x_i - \bar{x})^2$ |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| 8.4 | 70 | -6 | -50.4 | 36 |
| 9.5 | 22 | -4 | -38 | 24 |
| 11.8 | 24 | -2 | -23.6 | 4 |
| 10.4 | 26 | 0 | 0 | 0 |
| 13.3 | 28 | 2 | 26.6 | 4 |
| 14.8 | 30 | 4 | 59.2 | 16 |
| 13.2 | 32 | 6 | 79.2 | 36 |
| $\sum =$ 81.4 | 182 | 0 | 53 | 120 |

: Computation table

$\bar{x} = \frac{\sum (x_i)}{n} = \frac{182}{7} = 26$

\begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
    7 & 0\\
    0 & 120
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
    81.4 \\
    53
  \end{pmatrix}
\end{align*} \begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
    11.628\\
    0.441
  \end{pmatrix}
\end{align*}

$\therefore \text{The model is given by} \colon y_i = 11.628 + 0.441(x_i - \bar{x})$

------------------------------------------------------------------------

### Question 4

a.  Derive the estimators of $\beta_0 \ ,\beta_1 \  , \text{and} \ \sigma^2 \quad$ using the method of maximum likelihood. Assuming "$n$" random variables are jointly independent and each $y_i$ is a normal random variable $y_i \sim NIID(\beta_0 + \beta_1 x_i; \quad \sigma^2)$

b.  Complete the ANOVA table and test statistical significance of the regression coefficient at $\alpha = 5\%$

| Source of Variation | Degree of freedom | Sum of Squares | Mean Squares | F-calculated |
|---------------|---------------|---------------|---------------|---------------|
| Regressor (SSR) | $\underline{}$ | 5.3025 | 5.3025 | $\underline{}$ |
| Residual (SSE) | $\underline{}$ | $\underline{}$ | $\underline{}$ |  |
| Total | 199 | 11.51702 |  |  |

: where $F_{tab}(0.05) = 3.89$

### Solution

a.  $y_i = \beta_i + \beta_1x_i + e_i$

The regression model is:

$$
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
$$

Assume:

$$
y_i \mid x_i \sim N(\beta_0 + \beta_1 x_i, \sigma^2)
$$

The density function is:

$$
f(y_i \mid x_i, \beta, \sigma^2)
=
\frac{1}{\sqrt{2\pi\sigma^2}}
\exp\left(
-\frac{1}{2}
\frac{(y_i - \beta_0 - \beta_1 x_i)^2}{\sigma^2}
\right)
$$

Since the observations are independent, the joint likelihood is:

$$
L(\beta,\sigma^2)
=
\prod_{i=1}^{n}
\frac{1}{\sqrt{2\pi\sigma^2}}
\exp\left(
-\frac{1}{2}
\frac{(y_i - \beta_0 - \beta_1 x_i)^2}{\sigma^2}
\right)
$$

This simplifies to:

$$
L(\beta,\sigma^2)
=
\left(\frac{1}{\sqrt{2\pi\sigma^2}}\right)^n
\exp\left(
-\frac{1}{2\sigma^2}
\sum_{i=1}^{n}
(y_i - \beta_0 - \beta_1 x_i)^2
\right)
$$

Taking logs:

\begin{align*}
  L(\beta,\sigma^2)
  &=
  \left(\frac{1}{\sqrt{2\pi\sigma^2}}\right)^n
  \exp\left(
  -\frac{1}{2\sigma^2}
  \sum_{i=1}^{n}
  (y_i - \beta_0 - \beta_1 x_i)^2
  \right) \\
  \\
  \log L(\beta,\sigma^2)
  &=
  -\frac{n}{2} \log(2\pi\sigma^2)
  -
  \frac{1}{2\sigma^2}
  \sum_{i=1}^{n}
  (y_i - \beta_0 - \beta_1 x_i)^2
\end{align*}

Looks familiar, doesn't it?

To derive $\sigma^2$, we need to evaluate $\frac{\delta\log(\beta,\sigma^2)}{\delta\sigma^2}$ and equate it to $0$

\begin{align*}
  \Rightarrow \frac{\delta\log(\beta,\sigma^2)}{\delta\sigma^2}
  & = \frac{-n}{2} \cdot \frac{4\pi\sigma}{2\pi\sigma^2} 
  -\frac{1}{2} \sum 
  (y_i - \beta_0 - \beta_1 x_i)^2 \cdot 
  \left(\frac{-2}{\sigma^3}
  \right) \\
  
  \Rightarrow \frac{\delta\log(\beta,\sigma^2)}{\delta\sigma^2}
  & =
  -\frac{n}{\sigma} + \sum \frac{(y_i - \beta_0 - \beta_1 x_i)^2 }{\sigma^3}
\end{align*}

Equating to $0$: \begin{align*}
  \Rightarrow -\frac{n}{\sigma} + \sum \frac{(y_i - \beta_0 - \beta_1 x_i)^2}{\sigma^3}
   =
  0 \\
  \Rightarrow \frac{-n\sigma^2  + \sum (y_i - \beta_0 - \beta_1 x_i)^2}{\sigma^3} 
   =
  0 \\
  \Rightarrow -n\sigma^2  + \sum (y_i - \beta_0 - \beta_1 x_i)^2
  =
  0 \\
\end{align*} 

\begin{align*}
  \Rightarrow -n\sigma^2  
   & = 
   -\sum (y_i - \beta_0 - \beta_1 x_i)^2 \\
  
  \Rightarrow \sigma^2  
   & =
  \frac{-\sum (y_i - \beta_0 - \beta_1 x_i)^2}{-n} \\
  
  \Rightarrow \sigma^2  
   & =
  \frac{\sum (y_i - \beta_0 - \beta_1 x_i)^2}{n} \\
\end{align*}

\[
\boxed  {\Rightarrow \sigma^2  
    =
  \frac{\sum(e_i)^2}{n}
}
\]
To derive $\beta_0$, we evaluate $\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_0}$ and equate it to $0$

$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_0} 
=
0 - \frac{1}{2\sigma^2} \cdot \sum {(y_i - \beta_0 - \beta_1x_i)}^2
$$
$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_0} 
=
-\frac{1}{2\sigma^2} \cdot 2\sum {(y_i - \beta_0 - \beta_1x_i)}\cdot -1
$$

$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_0} 
=
-\frac{1}{2\sigma^2} \cdot 2\sum {(y_i - \beta_0 - \beta_1x_i)}\cdot -1
$$
$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_0} 
=
-\frac{1}{\sigma^2} \cdot\sum {(y_i - \beta_0 - \beta_1x_i)}\cdot -1
$$

$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_0} 
=
-\frac{1}{\sigma^2} \cdot\sum {(-y_i + \beta_0 + \beta_1x_i)}
$$
Equating to $0$
$$
-\frac{1}{\sigma^2} \cdot\sum {(-y_i + \beta_0 + \beta_1x_i)} = 0
$$
$$
\Rightarrow
\sum {(-y_i + \beta_0 + \beta_1x_i)} = 0
$$

\begin{align*} 
  \sum -y_i + \sum\beta_0 + \sum\beta_1x_i & = 0 \\
  
  -\sum y_i + n\beta_0 + \beta_1\sum x_i & = 0
\end{align*}

$$
\Rightarrow
n\beta_0  = \sum y_i - \beta_1\sum x_i
$$
\begin{align*}
  n\beta_0  & = \sum y_i - \beta_1\sum x_i \\
  \beta_0   & = \frac{\sum y_i}{n} - \beta_1\frac{\sum x_i}{n} \\
\end{align*}
\[
\boxed {\Rightarrow \beta_0 = \bar{y} - \beta_1\bar{x}}
\]

To derive $\beta_1$, we evaluate $\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_0}$ and equate it to $0$

$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_1} 
=
0 - \frac{1}{2\sigma^2} \cdot \sum {(y_i - \beta_0 - \beta_1x_i)}^2
$$
$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_1} 
=
-\frac{1}{2\sigma^2} \cdot 2\sum {(y_i - \beta_0 - \beta_1x_i)}\cdot -x_i
$$

$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_1} 
=
-\frac{1}{2\sigma^2} \cdot 2\sum {(-x_iy_i + x_i\beta_0 + \beta_1x_i^2)}
$$
$$
\frac{\delta\log(\beta,\sigma^2)}{\delta\beta_1} 
=
-\frac{1}{\sigma^2} \cdot \sum (-x_iy_i + x_i\beta_0 + \beta_1x_i^2)
$$

Equating to $0$
$$
-\frac{1}{\sigma^2} \cdot\sum {(-x_iy_i + x_i\beta_0 + \beta_1x_i^2)} = 0
$$
$$
\sum {(-x_iy_i + x_i\beta_0 + \beta_1x_i^2)} = 0
$$

$$ 
  \sum -x_iy_i + \beta_0\sum x_i + \beta_1\sum x_i^2  = 0 
$$

$$
\beta_1  = \frac{\sum x_iy_i -  \beta_0\sum x_i}{\sum x_i^2}
$$

Recall that:
$$
\beta_0    = \frac{\sum y_i}{n} - \beta_1\frac{\sum x_i}{n} 
$$
Substituting the value for $\beta_0$:
$$
\beta_1\sum x_i^2  =
{\sum x_iy_i - 
\left( \frac{\sum y_i}{n} - 
\beta_1\frac{\sum x_i}{n} \right) \cdot \sum x_i}
$$
$$
\beta_1\sum x_i^2  =
{\sum x_iy_i - 
\left( \frac{\sum x_iy_i}{n} - 
\beta_1\frac{({\sum x_i})^2}{n} \right)}
$$

$$
\beta_1\sum x_i^2  =
\sum x_iy_i - 
\left( \frac{\sum x_iy_i}{n} - 
\beta_1\frac{({\sum x_i})^2}{n} \right)
$$

$$
\beta_1\sum x_i^2  =
{\sum x_iy_i - 
 \frac{\sum x_iy_i}{n} +
\beta_1\frac{({\sum x_i})^2}{n} }
$$
Multiply through by $n$:
$$
\Rightarrow 
n\beta_1\sum x_i^2  =
n\sum x_iy_i - 
\sum x_iy_i +
\beta_1 \left( \sum x_i \right)^2
$$

$$
\Rightarrow 
n\beta_1\sum x_i^2 -
\beta_1 \left( \sum x_i \right)^2 =
n\sum x_iy_i - 
\sum x_iy_i 
$$

$$
\Rightarrow 
\beta_1\left( n\sum x_i^2 -
\left( \sum x_i \right)^2 \right) =
n\sum x_iy_i - 
\sum x_iy_i 
$$
\[
\boxed {
\Rightarrow 
\beta_1 =
\frac{n\sum x_iy_i - 
\sum x_iy_i}{ n\sum x_i^2 -
 \left(\sum x_i \right)^2}
}
\]

b.  *Confirm the solution to the missing values*

| Source of Variation | Degree of freedom | Sum of Squares | Mean Squares | F-calculated |
|---------------|---------------|---------------|---------------|---------------|
| Regressor (SSR) | $\underline{1}$ | 5.3025 | 5.3025 | $\underline{169.4089}$ |
| Residual (SSE) | $\underline{198}$ | $\underline{6.21452}$ | $\underline{0.0313}$ |  |
| Total | 199 | 11.51702 |  |  |

: Completed ANOVA Table

------------------------------------------------------------------------

### Question 5

A study was made to determine the stirring rate on the amount of impurity in paint produced by a chemical process. The study yielded the following data:

|               |     |     |      |      |      |      |
|---------------|-----|-----|------|------|------|------|
| Impurity      | 8.4 | 9.5 | 11.8 | 10.4 | 13.3 | 14.8 |
| Stirring Rate | 20  | 22  | 24   | 26   | 28   | 30   |

a.  Fit the model $y_i = \beta_0 + \beta_1 + e_i$ by obtaining the parameter estimates
b.  Compute the ANOVA to test for the adequacy of the model

### Solution

a.  Given the model $\colon \quad y_i = \beta_0 + \beta_1 + e_i$ The normal equation becomes: \begin{align*}
      \sum y_i & = n\beta_0 + \beta_1 \sum x_i  \\
      \sum y_ix_i & = \beta_0 \sum x_i  + \beta_1 \sum (x_i{^2}
    \end{align*}

The systems of equations: \begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \sum y_i \\
      \sum x_iy_i
    \end{pmatrix}
    & =
    \begin{pmatrix}
    n & \sum x_i\\
    \sum x_i & \sum x_i{^2}
  \end{pmatrix}
  
  \begin{pmatrix}
    \beta_0\\
    \beta_1
  \end{pmatrix} \\
  
\Rightarrow
  \begin{pmatrix}
    \beta_0\\
    \beta_1
  \end{pmatrix}
  & = 
  \begin{pmatrix}
    n & \sum x_i\\
    \sum x_i & \sum x_i{^2}
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
      \sum y_i \\
      \sum x_iy_i
    \end{pmatrix}
  
\end{align*}

| Impurity ($y$) | Stirring rate ($x$) | $x_i^2$ | $x_iy_i$ |
|:--------------:|:-------------------:|:-------:|:--------:|
|      8.4       |         20          |   400   |   168    |
|      9.5       |         22          |   484   |   209    |
|      11.8      |         24          |   576   |  283.2   |
|      10.4      |         26          |   679   |  270.4   |
|      13.3      |         28          |   784   |  372.2   |
|      14.8      |         30          |   900   |   444    |
|  $\sum=$ 68.2  |         150         |  3820   |   1747   |

: Computation Table

\begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
    6 & 150\\
    150 & 3820
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
    68.2 \\
    1747
  \end{pmatrix}
\end{align*} \begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
    3.633\\
    0.6
  \end{pmatrix}
\end{align*}

$$
\therefore \text{The model is given by} \colon \quad  y_i = -3.633 + 0.6x_i + \epsilon\_i
$$ b. To compute the ANOVA, we need to evaluate the sources of variations (Regressor, Residual or Error, and the Total) Recall from the partitioning of sum of squares we have that: \begin{align*}
    SST & = SSR + SSE \\ 
    \text{where} \quad SST & = \sum {(y_i - \bar{y})}^2 \\
    SSR & = \sum {(\hat{y_i} - \bar{y})}^2  \\
    SSE & = \sum {(\hat{y_i} - y)}^2
      \end{align*}

| $y$ | ${(y - \bar{y})}^2$ | ${(\hat{y} - \bar{y})}^2$ | ${(\hat{y} - y)}^2$ |
|:----------------:|:----------------:|:----------------:|:----------------:|
| 8.4 | 8.801 | 9 | 0.001 |
| 9.5 | 3.484 | 3.24 | 0.004 |
| 11.8 | 0.187 | 0.36 | 1.068 |
| 10.4 | 0.934 | 0.36 | 2.454 |
| 13.3 | 3.737 | 3.24 | 0.017 |
| 14.8 | 11.787 | 9.0 | 0.187 |
| $\sum=$ 68.2 | 28.933 | 25.2 | 3.733 |

: Computation Table

| Source of Variation | Degree of freedom | Sum of Squares (SS) | Mean Squares (MS) | F-calculated |
|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| Regressor (SSR) | 1 | 25.2 | 25.2 | 27 |
| Residual (SSE) | 4 | 3.73 | 0.93 |  |
| Total (SST) | 5 | 28.93 |  |  |

: ANOVA Table

To determine the accuracy of the model, we evaluate the $R^2$ value of the model.

This value tells us how much of the variations in $y$, the response variable can be explained by the variations in $x$, the explanatory variable. \begin{align*}
    R^2 & = \frac {SSR}{SST} \\
    R^2 & = \frac{25.2}{28.93} \\
    R^2 & = 0.87
  \end{align*}


$\Rightarrow \quad$ *87% of variations in the impurity can be explained by the variations in the stirring rate*


------------------------------------------------------------------------

### Question 6

Sidewall panels for the interior of an airplane are formed in a 1500-ton press. The unit manufacturing cost varies with the production lot size. The data shown below give the average cost per unit (in hundreds of dollars) for this product($y$) and the production lot size($x$). The table is as shown below:

|     |     |     |     |     |     |     |     |     |     |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| $X$ | 1.0 | 1.0 | 2.0 | 2.3 | 3.3 | 3.3 | 4.0 | 4.0 | 4.7 |
| $Y$ | 2.3 | 1.0 | 2.8 | 1.8 | 1.8 | 3.7 | 2.6 | 2.2 | 3.2 |

Given that the way the data follows indicates a second-order polynomial may be appropriate (Quadratic model).

a.  Obtain the parameter estimates
b.  Compare this with the linear case and hence test the adequacy of the model

### Solution

a.  A quadratic model is given by the equation $y_i = \beta_0 x_i + \beta_2 {x_i}^2 + e_i$ .The normal equation now becomes: \begin{align*}
      \sum y_i & = n\beta_0 + \beta_1 \sum x_i + \beta_2 \sum {x_i}^2    \\
      \sum x_iy_i & = \beta_0 \sum x_i + \beta_1\sum {x_i}^2  + \beta_2 \sum x_i{^3} \\
      \sum x_i{^2}y_i & = \beta_0 \sum x_i{^2} + \beta_1\sum x_i{^3}  + \beta_2 \sum x_i{^4}
    \end{align*}

\begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1 \\
      \beta_2
    \end{pmatrix}
    & =
    \begin{pmatrix}
     n &  \sum x_i &  \sum x_i{^2}\\
     \sum x_i & \sum x_i{^2} & \sum x_i{^3} \\
     \sum x_i{^2} & \sum x_i{^3} & \sum x_i{^4}
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
    \sum y_i\\
    \sum x_iy_i \\
    \sum x_i{^2}y_i
  \end{pmatrix}
\end{align*}

*Make the computation table and confirm the values yourself*

*If you are confused on how we got here, check previous similar solutions*

\begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1 \\
      \beta_2
    \end{pmatrix}
    & =
    \begin{pmatrix}
     9 &  25.6 &  87.160 \\
     25.6 & 87.160 & 352.864 \\
     87.160 & 352.864 & 1283.136
  \end{pmatrix}^{-1}
  
  \begin{pmatrix}
    21.4\\
    65.43 \\
    231.405
  \end{pmatrix}
\end{align*} \begin{align*}
  \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1 \\
      \beta_2
    \end{pmatrix}
    & = 
    \begin{pmatrix}
    1.785\\
    0.113 \\
    0.028
  \end{pmatrix}
\end{align*}

$$
\therefore \text{The model is given by} \colon \quad  y_i = 1.783 + 0.113x_i + 0.028{x_i}^2\\
\text{Parameter estimates} \colon \quad \beta_0 = 1.785 \quad  \beta_1 = 0.113 \quad \text{and} \quad \beta_2 = 0.028
$$

| Source of Variation | Degree of Freedom | Sum of Squares | Mean Squares | F-calculated |
|---------------|---------------|---------------|---------------|---------------|
| Regressor | 2 | 1.02 | 0.51 | 0.787 |
| Residual | 6 | 3.89 | 0.648 |  |
| Total | 8 | 4.91 |  |  |

: ANOVA Table

\begin{align*}
R^2 & = \frac{SSR}{SST} \\
R^2 & = \frac{1.02}{4.91} \\
R^2 & = 0.207
\end{align*}


$\Rightarrow \quad$ *20.7% of variations in the y can be explained by the variations x*
*This is clearly a poor model*

b.  The linear model is expressed as $y_i = \beta_0 + \beta_i \sum x_i^2$. The normal equations now becomes $\colon$ \begin{align*}
    \sum y_i & = n\beta_0 + \beta_1 \sum x_i  \\
    \sum y_ix_i & = \beta_0 \sum x_i  + \beta_1 \sum x_i{^2}
      \end{align*}

\begin{align*}
    \Rightarrow
    \begin{pmatrix}
      \beta_0\\
      \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
      n & \sum x_i\\
      \sum x_i & \sum x_i^2
    \end{pmatrix}^{-1}
    \begin{pmatrix}
      \sum x_i  \\
      \sum x_iy_i
    \end{pmatrix}
    \end{align*} \begin{align*}
      \Rightarrow
      \begin{pmatrix}
        \beta_0\\
        \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
    9 & 25.6\\
    25.6 & 87.160
    \end{pmatrix}^{-1}
    \begin{pmatrix}
    21.4 \\
    65.430
    \end{pmatrix}
    \end{align*} \begin{align*}
      \Rightarrow
      \begin{pmatrix}
        \beta_0\\
        \beta_1
    \end{pmatrix}
    & =
    \begin{pmatrix}
      1.473 \\
      0.318
    \end{pmatrix}
    \end{align*}

$$
\therefore \text{The model is given by} \colon \quad  y_i = 1.473 + 0.318x_i + e_i \\
\text{Parameter estimates} \colon \quad \beta_0 = 1.473 \quad \text{and} \quad \beta_1 = 0.113
$$

| Source of Variation | Degree of freedom | Sum of Squares | Mean Squares | F-calculated |
|---------------|---------------|---------------|---------------|---------------|
| Regressor | 1 | 1.449 | .1449 | 2.665 |
| Residual | 7 | 3.806 | 0.5437 |  |
| Total | 8 | 5.255 |  |  |

: ANOVA TABLE

\begin{align*}
R^2 & = \frac{SSR}{SST} \\
R^2 & = \frac{1.02}{4.91} \\
R^2 & = 0.207
\end{align*}

$\Rightarrow \quad$ *17.2% of variations in the y can be explained by the variations x*

We can safely conclude that the quadratic model is more accurate than the linear model
